### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by jm90m** [browniefed/examples#10]
Just wanted to say thanks for the awesome React Native tutorials on egghead, also thank you so much for having the code on github. Having the code on here, was really helpful 👍

**Comment by browniefed** [comment]
Thanks, these type of posts are great. Come June I'll be pumping out even more!

**Comment by jm90m** [comment]
@browniefed Awesome, ill be looking forward to it, my work finally adopted React the past few months, after using BackboneJS & Angular for years, I've got a lot to catch up on, so I've been trying to immerse myself in the whole React ecosystem.

**Comment by browniefed** [comment]
Awesome. If you have any specific questions or things you'd like to see let me know. I'm happy to answer questions, or even spin up videos/tutorials etc.
