### ISSUE TITLE
Unable to run your code

### ISSUE THREAD

**Issue by IgorGanapolsky** [browniefed/examples#12]
Hello,
I get an error:
<img width="422" alt="screen shot 2018-01-12 at 4 23 09 pm" src="https://user-images.githubusercontent.com/201209/34895704-e5fc01fe-f7b4-11e7-822a-361d3d7b2a57.png">

**Comment by browniefed** [comment]
Can you be a little more specific about which branch? This sounds like a bundling issue if anything.

**Comment by fukemy** [comment]
how to run project in simulator? im new in react native, thank
