### ISSUE TITLE
Items on the front view are not clickable

### ISSUE THREAD

**Issue by antonioRinaldo** [browniefed/examples#18]
I have clickable items on both views. When I click on the items on the front view, it's how clicking the items behind, on the back face. Any solution? Thanks

**Comment by browniefed** [comment]
Not sure exactly what you're referring to but you might need to add `pointer-events: 'none'` to the front face once it's turned to the back

**Comment by antonioRinaldo** [comment]
Ok, i solved differently but thanks for your tip!
